#!/usr/bin/env bash
# Install skill '{{SKILL_SLUG}}' from branch '{{BRANCH}}' for local testing.
# Generated by Skill Composer — https://agentskills.io
#
# Usage:
#   bash test-{{SKILL_SLUG}}.sh /path/to/your/local/skills-hub
#
set -euo pipefail

REPO_DIR="${1:-}"
BRANCH="{{BRANCH}}"
SKILL="{{SKILL_SLUG}}"

if [[ -z "$REPO_DIR" ]]; then
  echo "Usage: bash test-${SKILL}.sh /path/to/your/local/skills-hub"
  exit 1
fi

if [[ "$REPO_DIR" == http* || "$REPO_DIR" == git@* ]]; then
  echo "Pass a local clone path, not a URL."
  exit 1
fi

if [[ ! -d "$REPO_DIR/.git" ]]; then
  echo "Not a git repo: $REPO_DIR"
  exit 1
fi

if [[ ! -f "$REPO_DIR/cli/install.sh" ]]; then
  echo "cli/install.sh not found — is this skills-hub?"
  exit 1
fi

cd "$REPO_DIR"
CURRENT_BRANCH=$(git branch --show-current 2>/dev/null || git rev-parse --abbrev-ref HEAD)
STASHED=0
if ! git diff --quiet || ! git diff --staged --quiet; then
  git stash push -m "skills-composer: pre-test stash"
  STASHED=1
fi

git fetch origin "$BRANCH"
git checkout "$BRANCH"
bash cli/install.sh

echo "Skill '$SKILL' installed from branch '$BRANCH'."
echo "Run evals: bash cli/run-evals.sh $SKILL"
echo "Restore: git checkout $CURRENT_BRANCH && bash cli/install.sh"
[[ $STASHED -eq 1 ]] && echo "Then: git stash pop"
